mensagem do repositorio
ThundeRatz/Bixos-2018 pull request #21
Opened 2018-03-30 02:32 UTC by gabrielafanucchi

2018-03-30 02:32 UTC, d-nery approved these changes

2018-03-30 03:26 UTC, freitas-renato approved these changes

2018-03-30 12:47 UTC, tiagoshibata approved these changes

2018-04-01 15:02 UTC, erickotsuka approved these changes

2018-04-07 07:33 UTC, d-nery requested changes

2018-04-07 07:33 UTC, d-nery commented on C/Tarefa/1/main.c
> +void* main(int argc, char *argv[]) {
?

2018-04-07 21:03 UTC, erickotsuka requested changes
Crie outra branch para a tarefa 1 e outra para a tarefa 2 e faça Pull Requests separados para cada uma.

2018-04-28 19:12 UTC, closed without merging