lol
ThundeRatz/Bixos-2018 pull request #4
Opened 2018-03-24 23:34 UTC by Leonardo-Cassiano

2018-03-25 01:00 UTC, tiagoshibata commented
Não sei como foi dada a tarefa, mas o objetivo não era fazer por um cliente local? O GitHub está falando que você fez as mudanças pelo site. Para o dia a dia na equipe é importante saber usar algum cliente, principalmente para coisas mais complexas (conflitos, merges, rebases...).

2018-03-25 03:14 UTC, d-nery commented
É, realmente o ideal é você fazer pelo seu terminal

[s]só me diz onde vc viu essa info Shibata pq eu não to vendo asuhuashuh[/s]

2018-03-25 03:16 UTC, d-nery requested changes
Aaah, achei, acho que nunca tinha visto esse Verified hahaha

Bom, tente fazer novamente, mas usando seu terminal com os comandos dados em aula para realizar os commits, pode usar o site apenas para pedir o Pull Request

2018-03-25 13:31 UTC, tiagoshibata requested changes
Use algum cliente local (linha de comando ou um cliente gráfico)

2018-03-26 21:29 UTC, closed without merging

2018-03-26 21:29 UTC, d-nery commented
Fechado porque outro foi aberto