Tarefa 2 de C
ThundeRatz/Bixos-2018 pull request #42
Opened 2018-04-15 19:28 UTC by Markoloko1

2018-04-15 20:04 UTC, d-nery approved these changes
Você colocou os comandos de compilação no execute.sh em vez de compile.sh, mas estou dando approve, parece que está tudo ok

2018-04-15 20:04 UTC, d-nery commented on C/Tarefa/2/execute.sh
> +gcc -c main.c sensors.c sensors.h
Não precisa colocar .h nesse comando, além disso, é sempre bom utilizar as flags `-Wall -Wextra` para receber warnings de compilação

2018-04-15 20:04 UTC, d-nery commented on C/Tarefa/2/execute.sh
> +gcc -o tarefa2.exe main.c sensors.c sensors.h
Já que na linha anterior você gerou main.o e sensors.o, deveria colocá-los aqui, em vez do .c

2018-04-15 20:10 UTC, Markoloko1 commented
Ok!! Vou ficar mais atento. Obrigado

2018-04-15 21:15 UTC, erickotsuka requested changes
Parece ok, só um pequeno detalhe.

2018-04-15 21:15 UTC, erickotsuka commented on C/Tarefa/2/main.c
> +    for (int j = 0 ; j<=7 ; j++ )
O ideal era manter o loop infinito, para enviar os dados continuamente.

2018-04-15 22:12 UTC, erickotsuka commented on C/Tarefa/2/main.c
> +}
Isso é só um detalhe, não vou pedir para alterar para aprovar. Mas é bom ter um newline no fim do arquivo (um enter).

2018-04-15 22:15 UTC, erickotsuka approved these changes

2018-04-16 00:23 UTC, freitas-renato approved these changes

2018-04-16 04:35 UTC, tiagoshibata approved these changes

2018-04-16 04:35 UTC, tiagoshibata commented on C/Tarefa/2/main.c
> +}
E não precisa lembrar de dar o enter no final, configura seu editor pra sempre colocar ele.

2018-04-28 19:12 UTC, closed without merging